complianceOperator:
  image:
    registry: rgcrprod.azurecr.us
    name: ssf/compliance-operator
    tag: "0.0.1"
  imagePullPolicy: Always
  serviceAccountName: stigatron

heimdallOperator:
  image:
    registry: rgcrprod.azurecr.us
    name: ssf/heimdall-operator
    tag: "0.0.1"

  imagePullPolicy: Always 
  serviceAccountName: stigatron
  database:
    # If using an external postgres
    # host: postgres
    port: "5672"
    name: heimdall-server-production
    user: postgres
    password: password
    sslMode: false

prehook:
  image: ubuntu # TODO: SSF Built Tools Image
  tag: latest # TODO: SSF Built Tools Image
  imagePullPolicy: Always

rbac:
  roleName: compliance-operator
  roleBindingName: compliance-operator

alert:
  enabled: false

heimdall:
  # If using an external postgres
  # databaseHost: postgresql.example.com
  databasePort: 5432
  databaseName: heimdall-server-production
  databaseUsername: postgres
  databasePassword: password

  jwtSecret: abcde12345

  heimdall:
    image:
      registry: rgcrprod.azurecr.us
      name: carbide/heimdall
      tag: "0.0.1"
      pullPolicy: IfNotPresent
  
  postgresql:
    enabled: true
    # service:
    #   type: ClusterIP
    #   port: 5432
    persistence:
      enabled: false
      # size: "100Mi"
      # storageClassName: "default"
      # accessMode: "ReadWriteOnce"

