apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  username: {{ .Values.postgres.user | b64enc | quote }}
  password: {{ .Values.postgres.password | b64enc | quote }}
  jwt: {{ .Values.heimdall.jwtSecret | default (randAlphaNum 64) | b64enc | quote }}
  api: {{ .Values.heimdall.apiKeySecret | default (randAlphaNum 64) | b64enc | quote }}