proxy:
  imagePullPolicy: IfNotPresent
  image:
    registry: ""
    name: nginx
    tag: latest
  port: 8080
  service:
    type: ClusterIP
    port: 80

postgres:
  image:
    registry: ""
    name: postgresql
    tag: latest
  imagePullPolicy: IfNotPresent
  port: 5432
  service:
    type: ClusterIP
    port: 5432
  persistence:
    enabled: true
    persistentVolumeClaim: ""
    storageClassName: default
    storageRequest: 10Gi
    accessMode: RWO
  user: heimdall
  password: heimdall
  podAnnotations: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  affinity: {}
  tolrations: {}
heimdall:
  paths:
    # ONLY SET THESE VALUES IF YOU KNOW WHAT YOU ARE DOING
    # These are necessary for correct Heimdall operation
    # and are auto-detected in normal situations. 
    public: ""
    vue: ""
    router: ""
    axios: ""
  rcidf: # rancher-cluster-id-finder
    repository: ebauman/rcidf
    tag: v0.0.2
  databaseName: "heimdall"
  # repository: mitre/heimdall2
  # tag: 2.6.32
  image:
    registry: ""
    name: heimdall2
    tag: latest
  port: 80
  service:
    type: ClusterIP
    port: 80
  jwtExpireTime: 1d
  fleetNamespace: cattle-fleet-system

  # secret as in "secret value" not k8s secret
  # default is randAlphaNum 32
  apiKeySecret: ""

  # secret as in "secret value" not k8s secret
  # default is randAlphaNum 32
  jwtSecret: ""

  nodeEnv: "production" # leave it to this

  adminEmail: "admin@heimdall.local"

  # default is randomly generated
  # and available in pod logs after server init
  adminPassword: ""

  podAnnotations: {}

  selectorLabels: {}

  podSecurityContext: {}

  securityContext: {}

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}