# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

comingsoon:
  name: "carbide/comingsoon"
  tag: "0.1.0"
docs:
  rancher:
    enabled: true
    image:
      name: "carbide/rancher-docs"
      tag: "0.1.0"
  rke2:
    enabled: true
    image:
      name: "carbide/rke2-docs"
      tag: "0.1.0"
  k3s:
    enabled: true
    image:
      name: "carbide/k3s-docs"
      tag: "0.1.0"
  neuvector:
    enabled: true
    image:
      name: "carbide/neuvector-docs"
      tag: "0.1.0"
  fleet:
    enabled: true
    image:
      name: "carbide/fleet-docs"
      tag: "0.1.0"
  longhorn:
    enabled: true
    image:
      name: "carbide/longhorn-docs"
      tag: "0.1.0"
  kubewarden:
    enabled: true
    image:
      name: "carbide/kubewarden-docs"
      tag: "0.1.0"
  carbide:
    enabled: true
    image:
      name: "carbide/carbide-docs"
      tag: "0.1.0"
  elemental:
    enabled: true
    image:
      name: "carbide/elemental-docs"
      tag: "0.1.0"
  harvester:
    enabled: true
    image:
      name: "carbide/harvester-docs"
      tag: "0.1.0"
  hauler:
    enabled: true
    image:
      name: "carbide/hauler-docs"
      tag: "0.1.0"
  rancherDesktop:
    enabled: true
    image:
      name: "carbide/rancher-desktop-docs"
      tag: "0.1.0"
  nginx-base:
    enabled: true
    image:
      name: carbide/nginx-base
      tag: 0.1.0

global:
  cattle:
    systemDefaultRegistry: "rgcrprod.azurecr.us"
