# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  name: "ssf"
  tag: "0.1.0"

global:
  cattle:
    systemDefaultRegistry: "rgcrprod.azurecr.us"


