# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: carbide-system

image:
  name: "ssf"
  tag: "1.0.0"

global:
  cattle:
    systemDefaultRegistry: "rgcrprod.azurecr.us"


