# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: carbide-system

image:
  registry: "harbor.lark.lol"
  name: "carbide"
  tag: "1.0.0"


